/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class finnstr_libgdx_liquidfun_ParticleContact */

#ifndef _Included_finnstr_libgdx_liquidfun_ParticleContact
#define _Included_finnstr_libgdx_liquidfun_ParticleContact
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     finnstr_libgdx_liquidfun_ParticleContact
 * Method:    jniGetIndexA
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_finnstr_libgdx_liquidfun_ParticleContact_jniGetIndexA
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleContact
 * Method:    jniGetIndexB
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_finnstr_libgdx_liquidfun_ParticleContact_jniGetIndexB
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleContact
 * Method:    jniGetWeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleContact_jniGetWeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleContact
 * Method:    jniGetNormalX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleContact_jniGetNormalX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleContact
 * Method:    jniGetNormalY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleContact_jniGetNormalY
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
