/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup */

#ifndef _Included_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
#define _Included_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniDestroyParticlesInGroup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniDestroyParticlesInGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetBufferIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetBufferIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetGroupFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetGroupFlags
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniSetGroupFlags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniSetGroupFlags
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetMass
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetMass
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetInertia
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetInertia
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetCenterX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetCenterX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetCenterY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetCenterY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetLinVelocityX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetLinVelocityX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetLinVelocityY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetLinVelocityY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetAngularVelocity
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetAngularVelocity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetPositionX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetPositionX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetPositionY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetPositionY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniGetAngle
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniGetAngle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniApplyForce
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniApplyForce
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup
 * Method:    jniApplyLinearImpulse
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_liquidfun_ParticleGroup_jniApplyLinearImpulse
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
