/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class finnstr_libgdx_liquidfun_ParticleBodyContact */

#ifndef _Included_finnstr_libgdx_liquidfun_ParticleBodyContact
#define _Included_finnstr_libgdx_liquidfun_ParticleBodyContact
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     finnstr_libgdx_liquidfun_ParticleBodyContact
 * Method:    jniGetIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_finnstr_libgdx_liquidfun_ParticleBodyContact_jniGetIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleBodyContact
 * Method:    jniGetBodyAddr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_finnstr_libgdx_liquidfun_ParticleBodyContact_jniGetBodyAddr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleBodyContact
 * Method:    jniGetFixtureAddr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_finnstr_libgdx_liquidfun_ParticleBodyContact_jniGetFixtureAddr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleBodyContact
 * Method:    jniGetWeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleBodyContact_jniGetWeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleBodyContact
 * Method:    jniGetNormalX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleBodyContact_jniGetNormalX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleBodyContact
 * Method:    jniGetNormalY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleBodyContact_jniGetNormalY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleBodyContact
 * Method:    jniGetMass
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleBodyContact_jniGetMass
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
