/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class finnstr_libgdx_liquidfun_ParticleSystem */

#ifndef _Included_finnstr_libgdx_liquidfun_ParticleSystem
#define _Included_finnstr_libgdx_liquidfun_ParticleSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniCreateParticleSystem
 * Signature: (JFFFFFFFFFFFFFIFZFZFFI)J
 */
JNIEXPORT jlong JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniCreateParticleSystem
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jboolean, jfloat, jboolean, jfloat, jfloat, jint);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniDestroyParticleSystem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniDestroyParticleSystem
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniCreateParticle
 * Signature: (JIFFFFIIIIFZJ)I
 */
JNIEXPORT jint JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniCreateParticle
  (JNIEnv *, jobject, jlong, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jfloat, jboolean, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniDestroyParticle
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniDestroyParticle
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniDestroyOldestParticle
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniDestroyOldestParticle
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniDestroyParticleInShape
 * Signature: (JJFFF)I
 */
JNIEXPORT jint JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniDestroyParticleInShape
  (JNIEnv *, jobject, jlong, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniCreateParticleGroup
 * Signature: (JIIFFFFFFIIIIFJFIZFFFJ)J
 */
JNIEXPORT jlong JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniCreateParticleGroup
  (JNIEnv *, jobject, jlong, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jfloat, jlong, jfloat, jint, jboolean, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniJoinParticleGroups
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniJoinParticleGroups
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticlePositionBufferX
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticlePositionBufferX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticlePositionBufferY
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticlePositionBufferY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniUpdateParticlePositionBuffer
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniUpdateParticlePositionBuffer
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticlePositionBufferAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticlePositionBufferAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniUpdateParticlePositionAndColorBuffer
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniUpdateParticlePositionAndColorBuffer
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleVelocityBufferX
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleVelocityBufferX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleVelocityBufferY
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleVelocityBufferY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleColorBufferR
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleColorBufferR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleColorBufferG
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleColorBufferG
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleColorBufferB
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleColorBufferB
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleColorBufferA
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleColorBufferA
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniCalculateReasonableParticleIterations
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniCalculateReasonableParticleIterations
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniSetParticleRadius
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniSetParticleRadius
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleRadius
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleRadius
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleGroupCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleGroupCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniSetPaused
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniSetPaused
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetPaused
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetPaused
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniSetParticleDensity
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniSetParticleDensity
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleDensity
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleDensity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniSetParticleGravityScale
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniSetParticleGravityScale
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleGravityScale
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleGravityScale
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniSetParticleMaxCount
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniSetParticleMaxCount
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetMaxParticleCount
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetMaxParticleCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniSetParticleDamping
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniSetParticleDamping
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetParticleDamping
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetParticleDamping
  (JNIEnv *, jobject, jlong);

/*
 * Class:     finnstr_libgdx_liquidfun_ParticleSystem
 * Method:    jniGetVersionString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_finnstr_libgdx_liquidfun_ParticleSystem_jniGetVersionString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
